openapi: 3.0.0
info:
  title: Order Management System (OMS) API
  description: API for managing orders in the OMS.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server
paths:
  /orders:
    post:
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "201":
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateOrderResponse"
        "400":
          description: Invalid input
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
    get:
      summary: List orders
      operationId: listOrders
      parameters:
        - name: customer_id
          in: query
          required: true
          schema:
            type: string
          description: ID of the customer
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [PENDING_INVENTORY, CONFIRMED, CANCELLED]
          description: Filter by order status
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Filter by start date (ISO 8601)
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Filter by end date (ISO 8601)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: Number of items to return
        - name: next_token
          in: query
          required: false
          schema:
            type: string
          description: Pagination token
      responses:
        "200":
          description: List of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOrdersResponse"
        "400":
          description: Invalid query parameters
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error

  /orders/{id}:
    get:
      summary: Get an order by ID
      operationId: getOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "401":
          description: Unauthorized
        "404":
          description: Order not found
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error
    delete:
      summary: Delete an order by ID
      operationId: deleteOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        "204":
          description: Order deleted successfully
        "401":
          description: Unauthorized
        "404":
          description: Order not found
        "429":
          description: Too Many Requests
        "500":
          description: Internal Server Error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    CreateOrderRequest:
      type: object
      required:
        - customer_id
        - items
      properties:
        customer_id:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItemInput"

    OrderItemInput:
      type: object
      required:
        - sku
        - quantity
      properties:
        sku:
          type: string
        quantity:
          type: integer
          minimum: 1

    CreateOrderResponse:
      type: object
      properties:
        order_id:
          type: string

    ListOrdersResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
        next_token:
          type: string

    Order:
      type: object
      properties:
        id:
          type: string
        customer_id:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
        total:
          type: number
        status:
          type: string
          enum: [PENDING_INVENTORY, CONFIRMED, CANCELLED]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    OrderItem:
      type: object
      properties:
        sku:
          type: string
        quantity:
          type: integer
        price:
          type: number
        name:
          type: string

security:
  - ApiKeyAuth: []
